name: ec2-pipeline
on: workflow_dispatch
jobs:
  build-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 52.194.190.71
          username: ec2-user
          key: ${{ secrets.secretkey }}
          script: |
            cd /home/ec2-user
            python3 -m venv virtualenv
            source virtualenv/bin/activate
            pip3 install flask
            cat > app.py << 'EOF'
            from flask import Flask
            app = Flask(__name__)
            @app.route("/")
            def home():
                return "Hello from Team"
            if __name__ == "__main__":
                app.run(host="0.0.0.0", port=5001)
            EOF
            python3 app.py &